export const FETCH_PRICELIST_START = "FETCH_PRICELIST_START";
export const FETCH_PRICELIST_FAIL = "FETCH_PRICELIST_FAIL";
export const FETCH_PRICELIST_SUCCESS = "FETCH_PRICELIST_SUCCESS";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
